# Generated by Django 3.2.8 on 2023-03-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='ranking',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('ranking', models.IntegerField()),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_certification', to='Awards.certification')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_cert', to='Awards.certification')),
                ('title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Awards.title')),
            ],
        ),
    ]
