# Generated by Django 3.2.8 on 2023-03-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0002_auto_20230309_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_certification', to='Awards.certification'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_cert', to='Awards.certification'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Awards.title'),
        ),
    ]
