# Generated by Django 3.2.8 on 2023-03-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0004_auto_20230309_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='previous',
        ),
    ]
