# Generated by Django 3.2.8 on 2023-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0005_remove_certification_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certclass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
