# Generated by Django 3.2.8 on 2021-10-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cats', '0003_auto_20211008_2316'),
        ('People', '0003_person_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_nr', models.IntegerField()),
                ('guest', models.BooleanField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.person')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.CharField(default='', max_length=10)),
                ('biv', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('comment', models.CharField(default='', max_length=2048)),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shows.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('visibleToPublic', models.BooleanField(default=True)),
                ('openForRegistration', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=True)),
                ('entries', models.ManyToManyField(through='Shows.Entry', to='Cats.Cat')),
                ('judges', models.ManyToManyField(related_name='judged', through='Shows.Judge', to='People.Person')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized', to='People.person')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shows.show'),
        ),
        migrations.AddField(
            model_name='entry',
            name='judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement'),
        ),
        migrations.AddField(
            model_name='entry',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shows.show'),
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=3)),
                ('judgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shows.show')),
            ],
            options={
                'unique_together': {('show', 'catalog')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('show', 'catalog_nr')},
        ),
    ]
