# Generated by Django 3.2.8 on 2021-10-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shows', '0002_litter_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement'),
        ),
    ]
