# Generated by Django 3.2.8 on 2021-10-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0001_initial'),
        ('Shows', '0003_auto_20211009_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Awards.award')),
                ('judgement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shows.judgement')),
            ],
        ),
        migrations.AddField(
            model_name='judgement',
            name='nominations',
            field=models.ManyToManyField(through='Shows.Nomination', to='Awards.Award'),
        ),
    ]
