# Generated by Django 3.2.8 on 2021-10-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shows', '0005_show_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='judgement',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
