# Generated by Django 3.2.8 on 2023-03-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0003_auto_20230309_1747'),
        ('Cats', '0007_rename_organization_registry_organization'),
        ('Breeds', '0001_initial'),
        ('Shows', '0007_auto_20230309_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='judgement',
            name='ems',
        ),
        migrations.CreateModel(
            name='CatCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Awards.certification')),
                ('ems', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Breeds.ems')),
                ('judgement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement')),
            ],
        ),
    ]
