# Generated by Django 3.2.8 on 2023-03-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0001_initial'),
        ('Shows', '0009_alter_catcertification_judgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcertification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catcertification',
            name='ems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Breeds.ems'),
        ),
        migrations.AlterField(
            model_name='catcertification',
            name='judgement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shows.judgement'),
        ),
    ]
