# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shows', '0010_auto_20230310_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='catcertification',
            index=models.Index(fields=['cat'], name='Shows_catce_cat_id_4b1536_idx'),
        ),
        migrations.AddIndex(
            model_name='catcertification',
            index=models.Index(fields=['date'], name='Shows_catce_date_4da723_idx'),
        ),
        migrations.AddIndex(
            model_name='catcertification',
            index=models.Index(fields=['ems'], name='Shows_catce_ems_id_a5d8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['cat'], name='Shows_entry_cat_id_fd6959_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['show'], name='Shows_entry_show_id_43c957_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['name'], name='Shows_show_name_b35efe_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['date'], name='Shows_show_date_7eb6ee_idx'),
        ),
    ]
