# Generated by Django 3.2.8 on 2023-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shows', '0012_auto_20230313_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shows.judge'),
        ),
    ]
