# Generated by Django 3.2.8 on 2021-10-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25, unique=True)),
                ('category', models.IntegerField()),
                ('short', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True)),
                ('short', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeds.breed')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeds.color')),
            ],
        ),
    ]
