# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ems',
            index=models.Index(fields=['breed'], name='Breeds_ems_breed_i_72620b_idx'),
        ),
    ]
