# Generated by Django 3.2.8 on 2023-03-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0002_ems_breeds_ems_breed_i_72620b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ems',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
