# Generated by Django 3.2.8 on 2021-10-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('ssn', models.CharField(max_length=10, null=True, unique=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=3, null=True)),
                ('phoneNumber', models.CharField(max_length=25, null=True)),
                ('comment', models.CharField(max_length=2048, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
