# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_person_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='People_pers_name_e6b9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['ssn'], name='People_pers_ssn_28ad5c_idx'),
        ),
    ]
