# Generated by Django 3.2.8 on 2021-10-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catteries', '0001_initial'),
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('registration_class', models.CharField(default='', max_length=3, null=True)),
                ('country', models.CharField(default='', max_length=3, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('isMale', models.BooleanField()),
                ('neuter', models.DateField(blank=True, null=True)),
                ('cattery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Catteries.cattery')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dam_children', to='Cats.cat')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sire_children', to='Cats.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_date', models.DateField(null=True)),
                ('registry_number', models.CharField(max_length=20)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Microchip',
            fields=[
                ('microchip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
            ],
        ),
    ]
