# Generated by Django 3.2.8 on 2021-10-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='country',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
