# Generated by Django 3.2.8 on 2021-10-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0002_auto_20211008_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
