# Generated by Django 3.2.8 on 2021-10-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0003_auto_20211008_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='registry_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
