# Generated by Django 3.2.8 on 2021-12-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0001_initial'),
        ('Cats', '0004_alter_registry_registry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catcolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
                ('ems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeds.ems')),
            ],
        ),
    ]
