# Generated by Django 3.2.8 on 2022-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0005_catcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(blank=True, default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='registry',
            name='registry_number',
            field=models.CharField(max_length=20),
        ),
    ]
