# Generated by Django 3.2.8 on 2023-01-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0006_auto_20220331_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='Organization',
            new_name='organization',
        ),
    ]
