# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0007_rename_organization_registry_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['id'], name='Cats_cat_id_73ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['birth_date'], name='Cats_cat_birth_d_b26f40_idx'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['sire'], name='Cats_cat_sire_id_8450b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['dam'], name='Cats_cat_dam_id_20bdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['cat'], name='Cats_regist_cat_id_8c2586_idx'),
        ),
    ]
