# Generated by Django 3.2.8 on 2023-03-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catteries', '0002_cattery_catteries_c_name_e3fde1_idx'),
        ('Cats', '0008_auto_20230311_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='registration_class',
        ),
        migrations.AddField(
            model_name='registry',
            name='registration_class',
            field=models.CharField(default=' ', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='cattery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catteries.cattery'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='registry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
