# Generated by Django 3.2.8 on 2023-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0009_auto_20230313_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='registration_class',
        ),
        migrations.AddField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
