# Generated by Django 3.2.8 on 2023-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0010_auto_20230313_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='neuter',
            new_name='neuterDate',
        ),
        migrations.AddField(
            model_name='cat',
            name='isNeutered',
            field=models.BooleanField(default=False),
        ),
    ]
