# Generated by Django 3.2.8 on 2023-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0011_auto_20230313_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
