# Generated by Django 3.2.8 on 2023-03-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0012_alter_cat_registration_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='registration_class',
        ),
        migrations.AddField(
            model_name='registry',
            name='manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registry',
            name='registration_class',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
