# Generated by Django 3.2.8 on 2023-03-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_auto_20230313_1349'),
        ('Cats', '0016_alter_cat_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
    ]
