# Generated by Django 3.2.8 on 2023-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0018_auto_20230318_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='registry_number',
            field=models.CharField(max_length=32),
        ),
    ]
