# Generated by Django 3.2.8 on 2023-03-22 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0003_alter_ems_group'),
        ('Cats', '0019_alter_registry_registry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcolor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FenotypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cats.cat')),
                ('ems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeds.ems')),
            ],
        ),
    ]
