# Generated by Django 3.2.8 on 2023-03-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breeds', '0003_alter_ems_group'),
        ('Cats', '0020_auto_20230322_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FenotypeColor',
            new_name='PhenotypeColor',
        ),
    ]
