# Generated by Django 3.2.8 on 2023-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0022_auto_20230322_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcolor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotypecolor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
