# Generated by Django 3.2.8 on 2021-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
    ]
