# Generated by Django 3.2.8 on 2023-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
