# Generated by Django 3.2.8 on 2023-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_auto_20230313_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
