# Generated by Django 3.2.8 on 2021-10-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0003_person_organization'),
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registry_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('prefix', models.BooleanField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CatteryOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('time', models.DateField(null=True)),
                ('cattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catteries.cattery')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='People.person')),
            ],
        ),
    ]
