# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catteries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cattery',
            index=models.Index(fields=['name'], name='Catteries_c_name_e3fde1_idx'),
        ),
    ]
