# Generated by Django 3.2.8 on 2023-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catteries', '0002_cattery_catteries_c_name_e3fde1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattery',
            name='registry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
