# Generated by Django 3.2.8 on 2021-10-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0002_auto_20211008_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('joined', models.DateField(auto_now=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='People.person')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gift', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('method', models.CharField(max_length=128)),
                ('uri', models.CharField(max_length=7, unique=True)),
                ('members', models.ManyToManyField(to='Membership.Member')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid', to='Membership.member')),
            ],
        ),
    ]
