# Generated by Django 3.2.8 on 2021-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_auto_20211008_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
