# Generated by Django 3.2.8 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0004_member_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id'], name='Membership__id_5cbe3a_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['person'], name='Membership__person__6d3234_idx'),
        ),
    ]
